apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - dashboard-tailscale.yaml
  - dashboard-tailscale-v2.yaml
  - ingress.yaml
  # Note: Uncomment these scrapers after updating the IPs to match your cluster1 UDP relays
  # - scrape-aws-udp-relay-1.yaml
  # - scrape-aws-udp-relay-2.yaml

helmCharts:
  - name: prometheus-operator-crds
    repo: https://prometheus-community.github.io/helm-charts
    version: 19.1.0  # Replace with the desired version
    releaseName: prometheus-operator-crds
    namespace: monitoring
    includeCRDs: true
    valuesInline: {}
#   - name: kube-prometheus-stack
#     repo: https://prometheus-community.github.io/helm-charts
#     version: 70.7.0
#     namespace: monitoring
#     releaseName: kube-prometheus-stack
#     includeCRDs: true
#     valuesFile: values-kube-prometheus-stack.yaml