---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./default/ks.yaml
  - ./monitoring/ks.yaml
  - ./monitoring/namespace.yaml
  - ./tailscale/ks.yaml
  - ./tailscale/namespace.yaml
  - ./flux-system/ks.yaml
