---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- goldpinger.yaml
- ingress.yaml
- debug.yaml
- egress.yaml
- iperf-server.yaml
- iperf-client.yaml  # Note: Contains the ProxyGroup for egress
- nginx.yaml